# EDA with assembly report, clustering, slippage, and mol_type

In [2]:
import numpy as np
import pandas as pd

In [3]:
assembly = pd.read_csv("../assembly_data_report.csv")
slippage = pd.read_csv("../gff_results/gff_parsed.csv")
mol_type = pd.read_csv("../gff_results/mol_type_parsed.csv")
cluster = pd.read_csv("../clustering_results/clusterRes_cluster.tsv", sep='\t', names=["cluster", "ID"])
cluster = cluster.drop_duplicates(['cluster', 'ID'])

In [14]:
assembly.head()

,accession,assembly_level,assembly_name,submitter,total_sequence_length,gc_percent,taxid,organism_name,release_date
0,GCA_000320725.1,Contig,APLentillevirus_1.0,CNRS UMR IRD 6236,1193433,28.0,1077221,Acanthamoeba polyphaga lentillevirus,2012-07-27
1,GCA_000847085.1,Complete Genome,ViralProj14573,"M. Jaeger, Dept of Virology, University of Ulm...",4491,33.5,1977403,Acholeplasma phage MV-L51,1993-04-21
2,GCA_000848265.1,Complete Genome,ViralProj14654,"NIH, NLM",5894,55.0,11788,Abelson murine leukemia virus,1998-01-22
3,GCA_000850225.1,Complete Genome,ViralProj14710,"BMC, University of Latvia",4268,44.0,154784,Acinetobacter phage AP205,2003-01-30
4,GCA_000858405.1,Complete Genome,ViralProj15222,NaN,5234,40.0,185639,Acheta domestica densovirus,2002-02-04

In [11]:
slippage.head()

,Unnamed: 0,record_id,type,start,end,strand,qualifiers,search_term,source_file
0,0,MG982796.1,CDS,24,594,1,"{'ID': ['cds-AVT55874.1'], 'Parent': ['gene-PA...",slip,../viral_data_all/ncbi_dataset/data_subset/GCA...
1,1,MG982796.1,CDS,595,724,1,"{'ID': ['cds-AVT55874.1'], 'Parent': ['gene-PA...",slip,../viral_data_all/ncbi_dataset/data_subset/GCA...
2,2,MT090511.1,CDS,0,570,1,"{'ID': ['cds-QIC52522.1'], 'Parent': ['gene-PA...",slip,../viral_data_all/ncbi_dataset/data_subset/GCA...
3,3,MT090511.1,CDS,571,760,1,"{'ID': ['cds-QIC52522.1'], 'Parent': ['gene-PA...",slip,../viral_data_all/ncbi_dataset/data_subset/GCA...
4,4,MK624178.1,CDS,12,582,1,"{'ID': ['cds-QBL91539.1'], 'Parent': ['gene-PA...",slip,../viral_data_all/ncbi_dataset/data_subset/GCA...

In [47]:
mol_type

          record_id        accession     mol_type
0        AB000403.1  GCA_000847645.1  genomic RNA
1        AB000404.1  GCA_000847645.1  genomic RNA
2        AB000851.1  GCA_000871205.1  genomic RNA
3        AB000923.1  GCA_000840045.1  genomic DNA
4        AB000924.1  GCA_000840045.1  genomic DNA
...             ...              ...          ...
1326710    Z58828.2  GCA_002833845.1  genomic DNA
1326711    Z69620.1  GCA_000857785.1  genomic RNA
1326712    Z69910.1  GCA_000851225.1  genomic RNA
1326713    Z73124.1  GCA_000860665.1         mRNA
1326714    Z86099.2  GCA_003052145.1  genomic DNA

[1326715 rows x 3 columns]

In [46]:
cluster

            cluster          ID
0        MW334171.1  MW334171.1
1        MW334171.1  OP023516.1
2        MW334171.1  PQ755305.1
3        MW334171.1  PQ756818.1
4        MW334171.1  PQ756310.1
...             ...         ...
1326720  KP939613.1  KP939837.1
1326721  KP939613.1  KP940036.1
1326722  KP939613.1  KP940044.1
1326723  OP890528.1  OP890528.1
1326724  OQ469091.1  OQ469091.1

[1326596 rows x 2 columns]

In [4]:
cluster['cluster'].nunique()

50057

In [3]:
mol_type_cluster = mol_type.merge(cluster, right_on='ID', left_on='record_id').drop(columns='ID')

In [4]:
mol_type_cluster

          record_id        accession     mol_type      cluster
0        AB000403.1  GCA_000847645.1  genomic RNA   AB000403.1
1        AB000404.1  GCA_000847645.1  genomic RNA   AB000404.1
2        AB000851.1  GCA_000871205.1  genomic RNA  NC_009896.1
3        AB000923.1  GCA_000840045.1  genomic DNA   AB000923.1
4        AB000924.1  GCA_000840045.1  genomic DNA   AB000924.1
...             ...              ...          ...          ...
1326706    Z58828.2  GCA_002833845.1  genomic DNA  NC_043263.1
1326707    Z69620.1  GCA_000857785.1  genomic RNA  NC_002615.1
1326708    Z69910.1  GCA_000851225.1  genomic RNA  NC_003603.1
1326709    Z73124.1  GCA_000860665.1         mRNA  NC_003797.1
1326710    Z86099.2  GCA_003052145.1  genomic DNA     Z86099.2

[1326711 rows x 4 columns]